
name: Packer Validation

on:
  push:
    branches: [ main ]
  

jobs:

  packer:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    
    - name: Build Packer Template
      uses: ExitoLab/packer_build_action_aws@v0.2.10
      with:
        templateFile: 'ami.json'
        workingDir: 'packer'
        